### ISSUE TITLE
Expand schema to cover unique support levels for each framework version

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/supported-modules#5]
Currently the module list lacks any detail around:

- Which version of SilverStripe the module is supported under
- What level of support for the module is provided for any given SilverStripe version
- When this level of support will come to an end (based primarily on our roadmap)

The schema of the list needs to be updated to support this level of granularity, and we need to fill in this information where possible.

**Comment by robbieaverill** [comment]
>Which version of SilverStripe the module is supported under

We've talked about how to best implement this before, and I think the consensus was that we provide a "supported version constraint" which would define it, e.g. `^1.2` or `>=1.2 <4` for example. Some examples of modules that are commercially supported in some versions but not all are fluent, elemental, translatable and multivaluefield.

**Comment by GuySartorelli** [comment]
This information won't be maintained in this repo.
